set nocompatible
filetype off

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" Plugins goes here
Plugin 'hdima/python-syntax'
Plugin 'avakhov/vim-yaml'
Plugin 'airblade/vim-gitgutter'
Plugin 'kien/ctrlp.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'itchyny/lightline.vim'
Plugin 'itchyny/vim-gitbranch'
Plugin 'nvie/vim-flake8'
Plugin 'flazz/vim-colorschemes'
Plugin 'morhetz/gruvbox'
Plugin 'IN3D/vim-raml'
" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

" line numbers
set nu

" enable copy/paste from other applications
set clipboard=unnamed

" enable folding
set foldmethod=indent
set foldlevel=99

" enable folding with spacebar
nnoremap <space> za

" encoding
set encoding=utf-8

" make backspace work
set backspace=indent,eol,start

" split navigations
nnoremap <C-J> <C-W><C-J> " Ctrl-j move to the split below
nnoremap <C-K> <C-W><C-K> " Ctrl-k move to the split above
nnoremap <C-L> <C-W><C-L> " Ctrl-l move to the split to the right
nnoremap <C-H> <C-W><C-H> " Ctrl-h move to the split to the left

" Use the below highlight group when displaying bad whitespace is desired.
highlight BadWhitespace ctermbg=red guibg=red

" Display tabs at the beginning of a line in Python mode as bad.
au BufRead,BufNewFile *.py,*.pyw match BadWhitespace /^\t\+/

" Make trailing whitespace be flagged as bad.
au BufRead,BufNewFile *.py,*.pyw,*.c,*.h match BadWhitespace /\s\+$/

" configs for python-syntax plugin
let python_highlight_all=1

"syntax coloring

" Solarized
" let g:solarized_termcolors=256

syntax on
set background=dark
colorscheme gruvbox

" lightline
set laststatus=2
set noshowmode
let g:lightline = {
      \ 'colorscheme': 'gruvbox',
      \ 'active': {
      \   'right': [ [ 'lineinfo' ],
      \              [ 'percent' ],
      \              [ 'gitbranch', 'fileformat', 'fileencoding', 'filetype' ] ]
      \ },
      \ 'component_function': {
      \   'gitbranch': 'gitbranch#name'
      \ },
      \ }

" flake 8
let g:flake8_show_in_gutter=1
let g:flake8_show_quickfix=1

autocmd BufWritePost *.py call Flake8()
