source $HOME/.bash_aliases

# pyenv
if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi

# virtualenv wrapper
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/Projects
source /usr/local/bin/virtualenvwrapper.sh

# pip runs only on a virtualenv
export PIP_REQUIRE_VIRTUALENV="true"

# global pip

function gpip()
{
   PIP_REQUIRE_VIRTUALENV="" pip "$@"
}

function gpip3()
{
  PIP_REQUIRE_VIRTUALENV="" pip3 "$@"
}

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# Go lang
export GOPATH=$PROJECT_HOME/go

# Glacier
export LSCOLORS=excxFxFxBxxfxfxBxBxexe

function current_git_branch()
{
	git rev-parse --abbrev-ref HEAD 2> /dev/null | sed -e 's/.*/(&) /'
}

# export PS1="\W \\e[0;32m\$(current_git_branch)\e[m\] $ "
export PS1='\W \[\e[0;32m\]$(current_git_branch)\[\e[m\]$ '

# No more pyc files
export PYTHONDONTWRITEBYTECODE=1

# auto completion for git, my friend
if [ -f ~/.git-completion.bash ]; then
  . ~/.git-completion.bash
fi
